name: Webapp CI/CD workflow

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: self-hosted
    steps:
      - name: Test Step
        run: echo "Test step"

  build-backend:
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Test Step
        run: echo "Test step"

  deploy-to-prod:
    name: Deploy to PROD (K8S)
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    steps:
      - name: Test Step
        run: echo "Test step"

  api-tests-prod:
    name: API Tests on PROD
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - name: Test Step
        run: echo "Test step"

  backend-rollback:
    name: Backend Rollback
    runs-on: self-hosted
    needs: api-tests-prod
    steps:
      - name: Test Step
        run: echo "Test step"